### ISSUE TITLE
Markdox not working?

### ISSUE THREAD

**Issue by pootzko** [cbou/markdox#24]
Am I doing something wrong here or is markdox not working? 

I installed markdox through npm, downloaded this [fixture](https://github.com/cbou/markdox/blob/master/examples/fixtures/dox-parser.js) (I assume this is like a sample source file?) and after that I ran `markdox dox-parser.js` from the folder where _dox-parser.js_ was located. 

A file named _output.md_ got generated but it contained this:

```
<? docfiles.forEach(function(doc) { ?>

<!-- Start <?= doc.filename ?> -->

<? doc.javadoc.forEach(function(comment) { ?>
<? if (!comment.ignore) { ?>
<? if (comment.name) { ?>
<? if (comment.isMethod || comment.isFunction) { ?>
## <?= comment.name ?>(<?= comment.paramStr ?>)
<? } else { ?>
## <?= comment.name ?>
<? } ?>
<? } ?>

<?= comment.description ?>

<? if (comment.deprecated) { ?>
**Deprecated**
<? } ?>

<? if (comment.author) { ?>
Author: <?- comment.author ?>
<? } ?>

<? if (comment.version) { ?>
Version: <?= comment.version ?>
<? } ?>

<? if (comment.see) { ?>
See: <?= comment.see ?>
<? } ?>

<? if (comment.paramTags.length > 0) { ?>
### Params:
<? comment.paramTags.forEach(function(paramTag) { ?>
* **<?= paramTag.joinedTypes ?>** *<?= paramTag.name ?>* <?= paramTag.description ?><? }) ?>
<? } ?>

<? if (comment.returnTags.length > 0) { ?>
### Return:
<? comment.returnTags.forEach(function(returnTag) { ?>
* **<?= returnTag.joinedTypes ?>** <?= returnTag.description ?>
<? }) ?>
<? } ?>
<? } ?>
<? }) ?>

<!-- End <?= doc.filename ?> -->

<? }) ?>
```

Can you please tell me if I missed something here?

Thanks

**Comment by phun-ky** [comment]
I think it as something to do with https://github.com/tj/ejs, but I can't seem to narrow it down to the exact point. It looks like the template wont be compiled/rendered.

**Comment by copy** [comment]
For some reason, ejs seems to be ignoring the `ejs.open` and `ejs.close` properties. This can be fixed by grabbing the 1.0 version of ejs from https://github.com/tj/ejs (throw it into `markdox/node_modules`)

**Comment by eranimo** [comment]
Can we get a bower update using ejs version 1.0?

**Comment by jtuulos** [comment]
I just issued a PR to fix the dependency: https://github.com/cbou/markdox/pull/26

A temporary local fix is [shrinkwrapping](http://blog.nodejs.org/2012/02/27/managing-node-js-dependencies-with-shrinkwrap/) your `markdox` dependency:

1. Run `npm shrinkwrap [--dev]` (the flag is required if `markdox` is a `devDependency`)
1. Remove all other packages but `markdox` in the resulting file, `npm-shrinkwrap.json` (but keep anything under `markdox.dependencies`)
1. Find `ejs` under `markdox.dependencies` and change the version from `2.1.4` to `1.0.0` (example below)

```json
"ejs": {
  "version": "1.0.0",
  "from": "ejs@>=0.7.2",
  "resolved": "https://registry.npmjs.org/ejs/-/ejs-1.0.0.tgz"
},
```

**Comment by blainsmith** [comment]
Thanks for the fix @jtuulos

**Comment by cbou** [comment]
Thanks for the PR. Sorry for not having time to look at this.
