### ISSUE TITLE
Not complete variable types in output

### ISSUE THREAD

**Issue by phun-ky** [cbou/markdox#25]
Before #24 occured to me, the last weeks/months(?) of using markdox, I discovered that the `type`:

    <? _types.forEach(function(tag) {  ?>
      <? if(tag.types.length > 0 ) { ?>
      Type : <? tag.types.forEach(function(type){ ?> `<?= type ?>`  <? }) ?>
      Default : <? try{ if(comment.raw.ctx.value){ ?> `<?= comment.raw.ctx.value ?>` <? } }catch(e){} ?>
      <? } ?>
    <? }) ?>

Produced not complete strings, ie:

    `bjec` // or
    `trin` // or
    `umbe`

What could be the culprit here? This was with markdox `v0.1.4`, and I use a custom template, full source here: https://gist.github.com/phun-ky/a33258cfb396dd470dee

If i do not use a custom template, I get:

    **bjec**
    **trin**

**Comment by phun-ky** [comment]
Can I get a response here? *bump* This is reproducable with latest version 0.1.8

**Comment by cbou** [comment]
Sorry for not responding, I do not really have times to maintain this module.

Could you please provide a full non working example, with input and screnario how to reproduce the error? It would help me to understand your problem

**Comment by phun-ky** [comment]
First, to circumvent the issue, you can do this:

      <? _types.forEach(function(tag) {  ?>
        <? if(tag.types.length > 0 ) { ?>
        Type : <? tag.types.forEach(function(type){

        if(type === 'bjec'){ type = 'Object'; }
        if(type === 'trin'){ type = 'String'; }
        if(type === 'umbe'){ type = 'Number'; }
        if(type === 'unctio'){ type = 'Function'; }
        if(type === 'oolea'){ type = 'Boolean'; }

        ?> `<?= type ?>`  <? }) ?>
        Default : <? try{ if(comment.raw.ctx.value){ ?> `<?= comment.raw.ctx.value ?>` <? } }catch(e){} ?>
        <? } ?>
      <? }) ?>

**Comment by phun-ky** [comment]
Clone this repo: https://github.com/phun-ky/markdox-issue-25 then:

    npm install
    grunt readme

See the generated file README.md and docs/inc/internal_modules_api.md

**Comment by cbou** [comment]
This is because dox wants the parameters like this:

```
{string|Boolean}
```

This should works:

```javascript

/**
 * This should be a String
 *
 * @type  {string|Boolean}
 */
var _string = "",
/**
 * This should be an Object
 *
 * @type  {Object}
 */
_object    = {},
/**
 * This should be a Boolean
 *
 * @type  {Boolean}
 */
_boolean  = true;
```

**Comment by phun-ky** [comment]
When was this introduced? It worked fine before. I think this a breaking change and the versioning should reflect that..

Now I have to go change hundreds of files..

**Comment by cbou** [comment]
I didn't change anything and the example are even built with `{}`: https://github.com/cbou/markdox/blob/master/examples/fixtures/dox-parser.js

I think it's a change on the dox project.

**Comment by phun-ky** [comment]
Ok. Will have to roll up my sleeves then.  I think it could be wise stating in the README that markdox is based on that the documentation syntax supported is jsDoc ( I could'nt find it now in the README)

**Comment by cbou** [comment]
> Markdox is a documentation generator based on Dox and Markdown. It parse Javascript and even Coffeescript.

First line of https://github.com/cbou/markdox
