### ISSUE TITLE
Can we remove underscore?

### ISSUE THREAD

**Issue by IonicaBizau** [cbou/markdox#32]
I see that the only `underscore` function that is used is `defaults`. Can we remove the `underscore` dependency?

We could replace it with [`ul.merge`](https://github.com/IonicaBizau/node-ul#merge-obj1-obj2-obj3--objn).

**Comment by cbou** [comment]
Of course, feel free to push a pull request.

**Comment by IonicaBizau** [comment]
OK, letting it there for now...
