### ISSUE TITLE
@api is missing from list in README.md

### ISSUE THREAD

**Issue by webOS101** [cbou/markdox#51]
The `@api` tag is missing from the list of supported tags but is shown right there in the sample below.  One or the other of those is in error.

**Comment by cbou** [comment]
I added `@api`. What do you mean with `One or the other of those is in error.` ?

**Comment by webOS101** [comment]
Whoops, I missed your reply.  I meant that if you don't support `@api` you shouldn't have it in your sample.  Or, if you do support it, you should have that in your list of supported tags.  You've fixed it!
